from __future__ import annotations

if __package__:
    from .providers import (
        BootstrapStatePaths,
        DefaultActivation,
        InstallPaths,
        InstallTarget,
        ProviderArtifacts,
        ProviderModelSelection,
        ProviderModelSelectionSchema,
        ProviderRecommendedModelProfile,
        ProviderRoleModelConfig,
        ProviderRoleModelOption,
        ProviderSpec,
        all_providers,
        bootstrap_state_paths,
        get_provider,
        project_bootstrap_state_paths,
        resolve_project_root,
        project_state_key,
        resolve_install_target,
    )
else:  # pragma: no cover
    from providers import (
        BootstrapStatePaths,
        DefaultActivation,
        InstallPaths,
        InstallTarget,
        ProviderArtifacts,
        ProviderModelSelection,
        ProviderModelSelectionSchema,
        ProviderRecommendedModelProfile,
        ProviderRoleModelConfig,
        ProviderRoleModelOption,
        ProviderSpec,
        all_providers,
        bootstrap_state_paths,
        get_provider,
        project_bootstrap_state_paths,
        resolve_project_root,
        project_state_key,
        resolve_install_target,
    )

__all__ = [
    "BootstrapStatePaths",
    "DefaultActivation",
    "InstallPaths",
    "InstallTarget",
    "ProviderArtifacts",
    "ProviderModelSelection",
    "ProviderModelSelectionSchema",
    "ProviderRecommendedModelProfile",
    "ProviderRoleModelConfig",
    "ProviderRoleModelOption",
    "ProviderSpec",
    "all_providers",
    "bootstrap_state_paths",
    "get_provider",
    "project_bootstrap_state_paths",
    "resolve_project_root",
    "project_state_key",
    "resolve_install_target",
]
